definitions:
  internal_handlers.addGoodRequest:
    properties:
      description:
        maxLength: 255
        minLength: 3
        type: string
      name:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - name
    type: object
  internal_handlers.patchGoodReprioritiizeRequest:
    properties:
      newPriority:
        minimum: 0
        type: integer
    required:
    - newPriority
    type: object
  internal_handlers.updateGoodRequest:
    properties:
      description:
        type: string
      name:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - name
    type: object
info:
  contact:
    email: danil-vinogradov-92@mail.ru
    name: Danil Vinogradov
    url: http://t.me/japsty
  description: HEZZL backend trainee assignment 2024
  title: REST API Service
  version: "1.0"
paths:
  /good/create:
    post:
      consumes:
      - application/json
      description: Add a new good to the database
      parameters:
      - description: Project ID
        in: query
        name: projectId
        required: true
        type: integer
      - description: Good details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.addGoodRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: bad input
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Add a new good
      tags:
      - good
  /good/remove:
    delete:
      consumes:
      - application/json
      description: Delete a good by ID
      parameters:
      - description: Good ID
        in: path
        name: id
        required: true
        type: integer
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad input
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a good
      tags:
      - good
  /good/reprioritiize:
    patch:
      consumes:
      - application/json
      description: Change the priority of a good
      parameters:
      - description: Good ID
        in: path
        name: id
        required: true
        type: integer
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: integer
      - description: New priority details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.patchGoodReprioritiizeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad input
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Reprioritize a good
      tags:
      - goods
  /good/update:
    patch:
      consumes:
      - application/json
      description: Update details of an existing good
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: ProjectID
        in: path
        name: projectId
        required: true
        type: integer
      - description: Updated good details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.updateGoodRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad input
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update an existing good
      tags:
      - good
  /goods/list:
    get:
      consumes:
      - application/json
      description: Get list of goods with pagination parameters
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad input
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get list of goods
      tags:
      - good
swagger: "2.0"
